# Generated by Django 5.0.6 on 2026-01-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_alumno_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estatus',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PENDIENTE', 'Pendiente de Documentos'), ('BAJA', 'Baja Temporal')], default='ACTIVO', max_length=20),
        ),
    ]
