# Generated by Django 5.0.6 on 2026-02-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
