# Generated by Django 5.0.6 on 2026-06-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_password_plana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_plana',
        ),
    ]
