# Generated by Django 5.0.6 on 2026-06-04 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_asignatura_options_alter_asistencia_options_and_more'),
        ('users', '0011_user_password_plana'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(default='2026-1', help_text='Ejemplo: 2026-1 para Ene-Abr 2026', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes_grupo', to='academic.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupo', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Asignación Docente-Grupo',
                'verbose_name_plural': 'Asignaciones Docente-Grupo',
                'ordering': ['grupo', 'asignatura'],
                'unique_together': {('docente', 'grupo', 'asignatura', 'ciclo')},
            },
        ),
    ]
