# Generated by Django 6.0.6 on 2026-06-24 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_plantel_total_aulas'),
        ('users', '0013_docenteplantel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_inscribir_alumnos', models.BooleanField(default=False)),
                ('puede_generar_pagos', models.BooleanField(default=False)),
                ('puede_subir_comunicados', models.BooleanField(default=False)),
                ('puede_subir_horarios', models.BooleanField(default=False)),
                ('puede_ver_calificaciones', models.BooleanField(default=False)),
                ('puede_gestionar_grupos', models.BooleanField(default=False)),
                ('puede_ver_reportes', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuses.plantel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Personal',
            },
        ),
    ]
