# Generated by Django 6.0.6 on 2026-06-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_permisopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
