# Generated by Django 6.0.6 on 2026-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_tutor_codigo_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_plana',
        ),
        migrations.AddField(
            model_name='user',
            name='password_recuperable',
            field=models.CharField(blank=True, help_text='Contraseña actual, encriptada de forma reversible para poder mostrarla si el usuario la pierde.', max_length=255, null=True),
        ),
    ]
