# Generated by Django 6.0.6 on 2026-08-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_password_plana_user_password_recuperable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_verificacion',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
