# Generated by Django 6.0.6 on 2026-09-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_password_verificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'rol': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutores_asignados', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_asignados', to='users.tutor')),
            ],
            options={
                'unique_together': {('alumno', 'tutor')},
            },
        ),
    ]
