# Generated by Django 6.0.6 on 2026-09-06 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_plantel_total_aulas'),
        ('users', '0018_alumnotutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='campuses.plantel'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to=settings.AUTH_USER_MODEL),
        ),
    ]
