# Generated by Django 5.0.6 on 2026-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_plantel_nivel_educativo_alter_plantel_color_tema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='total_aulas',
            field=models.PositiveIntegerField(default=20, verbose_name='Capacidad de Aulas'),
        ),
    ]
