# Generated by Django 5.0.6 on 2026-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='nivel_educativo',
            field=models.CharField(choices=[('BASICA', 'Básica (Sec/Prepa)'), ('SUPERIOR', 'Superior (Universidad)')], default='BASICA', max_length=50),
        ),
        migrations.AlterField(
            model_name='plantel',
            name='color_tema',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantel',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
