# Generated by Django 5.0.6 on 2026-01-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0001_initial'),
        ('users', '0002_remove_user_plantel_id_user_foto_url_user_plantel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='campuses.plantel'),
        ),
    ]
