# Generated by Django 5.0.6 on 2026-06-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plana',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
