# Generated by Django 5.0.6 on 2026-06-07 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_plantel_total_aulas'),
        ('users', '0012_docentegrupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentePlantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planteles_asignados', to=settings.AUTH_USER_MODEL)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuses.plantel')),
            ],
            options={
                'unique_together': {('docente', 'plantel')},
            },
        ),
    ]
