# Generated by Django 5.0.6 on 2026-01-22 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('grado', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuses.plantel')),
                ('tutor', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_tutorados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
