# Generated by Django 5.0.6 on 2026-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_asistencia_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='aula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
