# Generated by Django 5.0.6 on 2026-01-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_asignatura_carrera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='docente',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'DOCENTE'}, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='seriacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.asignatura'),
        ),
    ]
