# Generated by Django 5.0.6 on 2026-02-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_remove_asignatura_grupo_asignatura_grupos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_de_carrera', to='academic.carrera'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grupos',
            field=models.ManyToManyField(related_name='asignaturas', to='academic.grupo', verbose_name='Grupos'),
        ),
    ]
