# Generated by Django 5.0.6 on 2026-06-04 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_alter_asignatura_options_alter_asistencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Primero agregar los campos nuevos
        migrations.AddField(
            model_name='asistencia',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academic.asignatura'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('R', 'Retardo')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        # 2. Luego eliminar el campo viejo
        migrations.RemoveField(
            model_name='asistencia',
            name='presente',
        ),
        # 3. Al final cambiar unique_together (ahora sí existe asignatura)
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'grupo', 'asignatura', 'fecha')},
        ),
    ]