# Generated by Django 5.0.6 on 2026-06-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_asistencia_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas/archivos/')),
                ('fecha_entrega', models.DateTimeField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='academic.grupo')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tarea', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='academic.tarea')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tareas/entregas/')),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('CALIFICADA', 'Calificada'), ('TARDE', 'Entrega tardía')], default='ENTREGADA', max_length=15)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('entregada_en', models.DateTimeField(auto_now_add=True)),
                ('calificada_en', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='academic.tarea')),
            ],
            options={
                'ordering': ['-entregada_en'],
                'unique_together': {('tarea', 'alumno')},
            },
        ),
    ]
