# Generated by Django 5.0.6 on 2026-06-05 18:49

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_actividad_publicada_actividad_publicada_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF / Documento'), ('VIDEO', 'Video'), ('IMAGEN', 'Imagen'), ('LINK', 'Enlace externo'), ('OTRO', 'Otro')], max_length=10)),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo')),
                ('url_externa', models.URLField(blank=True, help_text='YouTube, Drive, etc.', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Material de Apoyo',
                'verbose_name_plural': 'Materiales de Apoyo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
