# Generated by Django 5.0.6 on 2026-06-05 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_materialapoyo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialapoyo',
            options={'ordering': ['orden', '-creado_en'], 'verbose_name': 'Material de Apoyo'},
        ),
        migrations.AddField(
            model_name='materialapoyo',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialapoyo',
            name='url_externa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CarpetaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_material', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_material', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas_material', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Carpeta de Material',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='materialapoyo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='academic.carpetamaterial'),
        ),
        migrations.CreateModel(
            name='ComentarioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='academic.materialapoyo')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
