# Generated by Django 5.0.6 on 2026-06-13 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_planclase_temaclase'),
        ('campuses', '0003_plantel_total_aulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('destinatario', models.CharField(choices=[('TODOS', 'Todos los grupos'), ('GRUPO', 'Grupo específico'), ('DOCENTES', 'Solo docentes')], default='TODOS', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, help_text='Solo si destinatario es GRUPO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='academic.grupo')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados', to='campuses.plantel')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
