# Generated by Django 5.0.6 on 2026-06-13 05:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_comunicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='adjunto',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PDF, imagen u otro archivo adjunto (opcional)', max_length=255, null=True, verbose_name='adjunto'),
        ),
    ]
