# Generated by Django 6.0.6 on 2026-06-24 00:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_comunicado_adjunto'),
        ('campuses', '0003_plantel_total_aulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='horario')),
                ('subido_en', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_pdf', to='academic.grupo')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_pdf', to='campuses.plantel')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario PDF',
            },
        ),
    ]
