# Generated by Django 6.0.6 on 2026-06-24 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_horariopdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_tareas', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('pct_actividades', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('pct_asistencia', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('pct_examen', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('pct_proyecto', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_evaluacion', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_evaluacion', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_evaluacion', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Configuración de Evaluación',
                'unique_together': {('docente', 'grupo', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(choices=[('EXAMEN', 'Examen'), ('PROYECTO', 'Proyecto')], max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_parciales', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_parciales', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_dadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_parciales', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Evaluación Parcial',
                'unique_together': {('alumno', 'grupo', 'asignatura', 'rubro')},
            },
        ),
    ]
