# Generated by Django 6.0.6 on 2026-06-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_configevaluacion_evaluacionparcial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial'), (3, 'Tercer Parcial'), (4, 'Cuarto Parcial')])),
                ('nota_tareas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_actividades', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_asistencia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion_final', models.DecimalField(decimal_places=2, max_digits=4)),
                ('publicada', models.BooleanField(default=False)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_parciales', to=settings.AUTH_USER_MODEL)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_parciales', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_parciales', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Boleta Parcial',
                'verbose_name_plural': 'Boletas Parciales',
                'ordering': ['parcial', 'alumno__last_name'],
                'unique_together': {('alumno', 'grupo', 'asignatura', 'parcial')},
            },
        ),
    ]
