# Generated by Django 6.0.6 on 2026-07-01 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_boletaparcial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clase', to='academic.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clase', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_clase', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clase',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='BloqueClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto / Indicación'), ('pdf', 'PDF / Documento'), ('video', 'Video'), ('imagen', 'Imagen'), ('link', 'Enlace externo'), ('actividad', 'Actividad')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contenido', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='academic.sesionclase')),
            ],
            options={
                'verbose_name': 'Bloque de Clase',
                'verbose_name_plural': 'Bloques de Clase',
                'ordering': ['orden', 'creado_en'],
            },
        ),
    ]
