# Generated by Django 6.0.6 on 2026-07-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_sesionclase_bloqueclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='asignatura',
            field=models.ForeignKey(blank=True, help_text='Materia relacionada (opcional). Vacío = comunicado general.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='academic.asignatura'),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='publico',
            field=models.CharField(choices=[('ALUMNOS', 'Solo alumnos'), ('PADRES', 'Solo padres'), ('AMBOS', 'Alumnos y padres')], default='AMBOS', help_text='A quién le llega: solo alumnos, solo padres, o ambos.', max_length=10),
        ),
    ]
