# Generated by Django 6.0.6 on 2026-07-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0033_comunicado_asignatura_comunicado_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temaclase',
            name='asignatura',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas_clase', to='academic.asignatura'),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='bloques',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='docente',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas_clase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='finalizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='grupo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas_clase', to='academic.grupo'),
        ),
        migrations.AddField(
            model_name='temaclase',
            name='iniciada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='temaclase',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('docente',), name='uq_temaclase_docente_una_activa'),
        ),
    ]
