# Generated by Django 6.0.6 on 2026-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_temaclase_asignatura_temaclase_bloques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionclase',
            name='activa',
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='borrador', max_length=20),
        ),
    ]
