# Generated by Django 6.0.6 on 2026-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_remove_sesionclase_activa_sesionclase_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaactividad',
            name='tipo',
            field=models.CharField(choices=[('MULTIPLE', 'Opción múltiple'), ('VF', 'Verdadero / Falso'), ('ABIERTA', 'Respuesta corta')], default='MULTIPLE', max_length=10),
        ),
    ]
