# Generated by Django 6.0.6 on 2026-08-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0036_preguntaactividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntaactividad',
            name='tipo',
            field=models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('verdadero_falso', 'Verdadero / Falso'), ('respuesta_corta', 'Respuesta corta')], default='opcion_multiple', max_length=20),
        ),
    ]
