# Generated by Django 6.0.6 on 2026-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_alter_preguntaactividad_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configevaluacion',
            name='pct_actividades',
        ),
        migrations.RemoveField(
            model_name='configevaluacion',
            name='pct_asistencia',
        ),
        migrations.RemoveField(
            model_name='configevaluacion',
            name='pct_examen',
        ),
        migrations.RemoveField(
            model_name='configevaluacion',
            name='pct_proyecto',
        ),
        migrations.RemoveField(
            model_name='configevaluacion',
            name='pct_tareas',
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='rubros',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
