# Generated by Django 6.0.6 on 2026-08-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_remove_configevaluacion_pct_actividades_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configevaluacion',
            old_name='rubros',
            new_name='rubros_extra',
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='pct_actividades',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='pct_asistencia',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='pct_examen',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='pct_proyecto',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='configevaluacion',
            name='pct_tareas',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
