# Generated by Django 6.0.6 on 2026-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_rename_rubros_configevaluacion_rubros_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletaparcial',
            name='notas_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evaluacionparcial',
            name='rubro',
            field=models.CharField(choices=[('EXAMEN', 'Examen'), ('PROYECTO', 'Proyecto')], max_length=30),
        ),
    ]
