# Generated by Django 6.0.6 on 2026-08-20 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0040_boletaparcial_notas_extra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='parcial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='parcial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evaluacionparcial',
            name='parcial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tarea',
            name='parcial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CierreParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.PositiveSmallIntegerField()),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_parcial', to='academic.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_parcial', to='academic.grupo')),
            ],
            options={
                'unique_together': {('grupo', 'asignatura', 'parcial')},
            },
        ),
    ]
