# Generated by Django 6.0.6 on 2026-08-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_actividad_parcial_asistencia_parcial_and_more'),
    ]

    operations = [
    ]
