# Generated by Django 6.0.6 on 2026-08-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_poblar_periodo_historico'),
        ('campuses', '0003_plantel_total_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='periodo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='academic.periodo'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='periodo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='academic.periodo'),
        ),
        migrations.AddField(
            model_name='evaluacionparcial',
            name='periodo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_parciales', to='academic.periodo'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='periodo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='academic.periodo'),
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('plantel',), name='uq_periodo_un_activo_por_plantel'),
        ),
    ]
