# Generated by Django 6.0.6 on 2026-08-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_actividad_periodo_asistencia_periodo_and_more'),
    ]

    operations = [
    ]
