# Generated by Django 6.0.6 on 2026-08-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_poblar_periodo_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='tipo',
            field=models.CharField(default='regular', max_length=50),
        ),
    ]
