# Generated by Django 6.0.6 on 2026-08-22 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0045_periodo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionparcial',
            unique_together={('alumno', 'grupo', 'asignatura', 'rubro', 'parcial')},
        ),
    ]
