# Generated by Django 6.0.6 on 2026-08-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0046_alter_evaluacionparcial_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('QUIMICO_BIOLOGICO', 'Químico-Biológico'), ('FISICO_QUIMICO', 'Físico-Químico'), ('ECONOMICO_ADMIN', 'Económico-Administrativo'), ('HISTORICO_SOCIAL', 'Histórico-Social')], help_text='Solo aplica de 5° a 6° semestre en Preparatoria.', max_length=30, null=True),
        ),
    ]
