# Generated by Django 6.0.6 on 2026-08-22 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0047_grupo_especialidad'),
        ('campuses', '0003_plantel_total_aulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(condition=models.Q(('especialidad__isnull', True)), fields=('plantel', 'periodo', 'carrera', 'grado'), name='unique_grupo_general_sin_especialidad'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(condition=models.Q(('especialidad__isnull', False)), fields=('plantel', 'periodo', 'carrera', 'grado', 'especialidad'), name='unique_grupo_por_especialidad'),
        ),
    ]
