# Generated by Django 5.0.6 on 2026-01-22 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='tutor',
        ),
        migrations.AddField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(blank=True, help_text='Solo para nivel Universidad (ej: Arquitectura, Psicología)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='docentes',
            field=models.ManyToManyField(limit_choices_to={'rol': 'DOCENTE'}, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.CharField(choices=[('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria'), ('UNIVERSIDAD', 'Universidad')], default='SECUNDARIA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
