# Generated by Django 5.0.6 on 2026-01-22 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.periodo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.CharField(blank=True, help_text='Solo para nivel Universidad', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
