# Generated by Django 5.0.6 on 2026-01-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_grupo_fecha_fin_grupo_fecha_inicio_grupo_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='aula',
            field=models.CharField(blank=True, help_text='Ej: Edificio B - 102', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='capacidad_maxima',
            field=models.IntegerField(default=30),
        ),
    ]
