# Generated by Django 5.0.6 on 2026-01-27 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_asistencia_options_alter_calificacion_options_and_more'),
        ('campuses', '0003_plantel_total_aulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['grado', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='nivel',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='seriacion',
            field=models.ForeignKey(blank=True, help_text='Materia requisito', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.asignatura'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'DOCENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academic.asignatura'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'DOCENTE'}, related_name='grupos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grado',
            field=models.IntegerField(verbose_name='Grado o Semestre'),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.CharField(choices=[('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria'), ('UNIVERSIDAD', 'Universidad')], max_length=20)),
                ('clave_rvoe', models.CharField(blank=True, max_length=50, null=True)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campuses.plantel')),
            ],
        ),
        migrations.AlterField(
            model_name='grupo',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academic.carrera'),
        ),
    ]
