# Generated by Django 5.0.6 on 2026-01-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_grupo_options_remove_grupo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academic.carrera'),
            preserve_default=False,
        ),
    ]
