# Generated by Django 5.0.6 on 2026-02-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_horarioclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grupo',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grupos',
            field=models.ManyToManyField(related_name='asignaturas', to='academic.grupo', verbose_name='Grupos que cursan esta materia'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_carrera', to='academic.carrera'),
        ),
    ]
