# Generated by Django 5.0.6 on 2026-06-04 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_alter_asignatura_carrera_alter_asignatura_grupos'),
        ('campuses', '0003_plantel_total_aulas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asistencia', 'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nivel', 'nombre'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['grado', 'nombre'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='asignaturas', to='academic.grupo', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='seriacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_subsecuentes', to='academic.asignatura'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academic.grupo'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='campuses.plantel'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.periodo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='campuses.plantel'),
        ),
        migrations.AlterField(
            model_name='horarioclase',
            name='maestro',
            field=models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'grupo', 'fecha')},
        ),
    ]
