# Generated by Django 5.0.6 on 2026-06-04 20:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_tarea_comentariotarea_entregatarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregatarea',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo'),
        ),
    ]
