# Generated by Django 5.0.6 on 2026-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_actividad_entregaactividad_preguntaactividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actividad',
            name='publicada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
