# Generated by Django 5.0.6 on 2026-06-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_alter_materialapoyo_options_materialapoyo_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
