# Generated by Django 5.0.6 on 2026-06-07 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_tarea_publicada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academic.grupo'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo',
            field=models.CharField(choices=[('MANUAL', 'Captura manual'), ('TAREA', 'Tarea'), ('ACTIVIDAD', 'Actividad')], default='MANUAL', max_length=15),
        ),
    ]
