# Generated by Django 5.0.6 on 2026-06-07 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_calificacion_docente_calificacion_grupo_and_more'),
        ('campuses', '0003_plantel_total_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='campuses.plantel'),
        ),
    ]
