# Generated by Django 5.0.6 on 2026-06-09 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_periodo_plantel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('periodo_tipo', models.CharField(choices=[('SEMANA', 'Semanal'), ('QUINCENA', 'Quincenal'), ('MES', 'Mensual'), ('BIMESTRE', 'Bimestral'), ('SEMESTRE', 'Semestral'), ('ANUAL', 'Anual')], default='MES', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('objetivo_general', models.TextField(blank=True, verbose_name='Objetivo general')),
                ('competencias', models.TextField(blank=True, verbose_name='Competencias a desarrollar')),
                ('publicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_clase', to='academic.asignatura')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='planes_clase', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_clase', to='academic.grupo')),
            ],
            options={
                'verbose_name': 'Plan de Clase',
                'verbose_name_plural': 'Planes de Clase',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TemaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='# Sesión')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('duracion_min', models.PositiveIntegerField(default=50, verbose_name='Duración (min)')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos / materiales')),
                ('evaluacion', models.TextField(blank=True, verbose_name='Instrumento de evaluación')),
                ('completado', models.BooleanField(default=False)),
                ('notas_docente', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='academic.planclase')),
            ],
            options={
                'verbose_name': 'Tema / Sesión',
                'verbose_name_plural': 'Temas / Sesiones',
                'ordering': ['numero'],
                'unique_together': {('plan', 'numero')},
            },
        ),
    ]
